### ISSUE TITLE
Formalise license and version format to add this to Bioconda

### ISSUE THREAD

**Issue by pcm32** [carlosproca/autospill#2]
Hi there!

Thanks for this great tool. I'm currently packaging it for bioconda to use it within Galaxy, but for bioconda this needs to have:

- A formalised license (GPL, LGPL, MIT, or other; essentially a known license model that allows re-distribution)
- Format the version to the proper semantic versioning standard, in this case for the current version should be 0.1.0 if I'm not mistaken.

Happy to PR, but specially the first one is a decision that you need to make.

Thanks!

**Comment by pcm32** [comment]
Also, it would be useful to know if you plan to add this to cran or bioconductor, to make the recipe consume it from there instead in the future. Thanks!

**Comment by pcm32** [comment]
FYI https://github.com/bioconda/bioconda-recipes/pull/28448 (let me know if I should put your github login under the recipe maintainer - it doesn't really have much implications AFAIK).

**Comment by carlosproca** [comment]
Hi @pcm32. 

Thank you for your comments! The license is MIT, and I have just released a new version 0.2.0, with no leading zeroes. 

Concerning CRAN/Bioconductor, the plan is to add the package to Bioconductor, but the date is still undecided. 

Regards
