### ISSUE TITLE
Expected running time for first example dataset MM1? Current ~8 hours and still running.

### ISSUE THREAD

**Issue by pcm32** [carlosproca/autospill#3]
Hi there!

I tried running the first dataset example with the calculate_compensation_paper.r script on a 2.5 GHz Dual core Intel Core i7. I see 4 R threads running for ~8 hours now (and is not done yet). Is that expected running time or I should be looking into something else in detail as this is too long for the MM1 dataset?

Thanks!

**Comment by carlosproca** [comment]
(Dealt with by email)
